### ISSUE TITLE
UI logout

### ISSUE THREAD

**Issue by SebasMelendez** [SebasMelendez/labcheck#6]
as a user I want to have some form to logout of the app so that I can close my session for other users on the same machine 

acceptance criteria
The User interface should allow to logout with the click of a button
user interface should return to the login screen once logged out

**Comment by brendasosa0721** [comment]
Log out button has been added to the website. When logout click it will take it back to the main page which is the log in page.

**Comment by dopecello** [comment]
Please push what you have to your branch or make a PR so other collaborators can see/verify that this issue is satisfied.

Issue will be closed once team is on board.

**Comment by dopecello** [comment]
Just need to create a session for the Student and then we can close this

**Comment by dopecello** [comment]
Need to render Logout button when logged in and then can close this
